# Generated by Django 6.0.2 on 2026-03-24 21:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('montant_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nombre_participants', models.IntegerField()),
                ('participants_payes', models.IntegerField(default=0)),
                ('montant_collecte', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('nb_jours', models.IntegerField()),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_expiration', models.DateTimeField()),
                ('statut', models.CharField(choices=[('active', 'Active'), ('complete', 'Complète'), ('expiree', 'Expirée'), ('stoppee', 'Stoppée')], default='active', max_length=20)),
                ('slug', models.CharField(max_length=16, unique=True)),
                ('deep_link', models.CharField(blank=True, max_length=200)),
                ('numero_receveur', models.CharField(max_length=20)),
                ('est_recurrente', models.BooleanField(default=False)),
                ('config_recurrence', models.JSONField(blank=True, null=True)),
                ('paydunya_invoice_url', models.URLField(blank=True)),
                ('supprime', models.BooleanField(default=False)),
                ('date_suppression', models.DateTimeField(blank=True, null=True)),
                ('stoppee_le', models.DateTimeField(blank=True, null=True)),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotisations_creees', to=settings.AUTH_USER_MODEL)),
                ('supprime_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotisations_supprimees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cotisations',
            },
        ),
        migrations.CreateModel(
            name='CommentaireCotisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('reponse_admin', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_reponse', models.DateTimeField(blank=True, null=True)),
                ('supprime', models.BooleanField(default=False)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to=settings.AUTH_USER_MODEL)),
                ('cotisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='cotisations.cotisation')),
            ],
            options={
                'db_table': 'commentaires_cotisations',
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_avec_frais', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nb_unites', models.IntegerField(default=1)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('paye', 'Payé'), ('rembourse', 'Remboursé')], default='en_attente', max_length=20)),
                ('rang_paiement', models.IntegerField(blank=True, null=True)),
                ('paydunya_token', models.CharField(blank=True, max_length=200)),
                ('date_participation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('supprime', models.BooleanField(default=False)),
                ('date_suppression', models.DateTimeField(blank=True, null=True)),
                ('cotisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='cotisations.cotisation')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'participations',
            },
        ),
        migrations.AddIndex(
            model_name='cotisation',
            index=models.Index(fields=['createur', 'statut'], name='cotisations_createu_f9c710_idx'),
        ),
        migrations.AddIndex(
            model_name='cotisation',
            index=models.Index(fields=['slug'], name='cotisations_slug_e41918_idx'),
        ),
        migrations.AddIndex(
            model_name='cotisation',
            index=models.Index(fields=['statut', 'date_expiration'], name='cotisations_statut_1c99e6_idx'),
        ),
        migrations.AddIndex(
            model_name='cotisation',
            index=models.Index(fields=['supprime'], name='cotisations_supprim_3ba208_idx'),
        ),
        migrations.AddIndex(
            model_name='cotisation',
            index=models.Index(fields=['date_creation'], name='cotisations_date_cr_4268ad_idx'),
        ),
        migrations.AddIndex(
            model_name='commentairecotisation',
            index=models.Index(fields=['cotisation', 'date_creation'], name='commentaire_cotisat_a3ac4f_idx'),
        ),
        migrations.AddIndex(
            model_name='participation',
            index=models.Index(fields=['cotisation', 'statut'], name='participati_cotisat_2705ad_idx'),
        ),
        migrations.AddIndex(
            model_name='participation',
            index=models.Index(fields=['participant', 'statut'], name='participati_partici_432808_idx'),
        ),
        migrations.AddIndex(
            model_name='participation',
            index=models.Index(fields=['supprime'], name='participati_supprim_8f3981_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together={('cotisation', 'participant')},
        ),
    ]
