# Generated by Django 6.0.2 on 2026-03-24 21:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('paiement_recu', 'Paiement reçu'), ('cotisation_complete', 'Cotisation complète'), ('cotisation_expiree', 'Cotisation expirée'), ('quickpay_expire', 'Quick Pay expiré'), ('quickpay_paye', 'Quick Pay payé'), ('verification_approuvee', 'Vérification approuvée'), ('verification_rejetee', 'Vérification rejetée'), ('nouvelle_connexion', 'Nouvelle connexion'), ('sanction', 'Sanction'), ('remboursement', 'Remboursement'), ('ambassadeur', 'Ambassadeur'), ('promo_verification', 'Promo vérification'), ('rappel_cotisation', 'Rappel cotisation'), ('whatsapp_panne', 'WhatsApp en panne'), ('systeme', 'Système'), ('reponse_commentaire', 'Réponse commentaire')], max_length=30)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('lue', models.BooleanField(default=False)),
                ('data', models.JSONField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('supprime', models.BooleanField(default=False)),
                ('date_suppression', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['user', 'lue'], name='notificatio_user_id_24f3ff_idx'), models.Index(fields=['user', 'date_creation'], name='notificatio_user_id_327175_idx'), models.Index(fields=['supprime'], name='notificatio_supprim_f693a6_idx')],
            },
        ),
    ]
