# Generated by Django 6.0.2 on 2026-03-24 21:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickPay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=11, unique=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_avec_frais', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frais_kotizo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('numero_receveur', models.CharField(max_length=20)),
                ('numero_payeur', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('paye', 'Payé'), ('expire', 'Expiré')], default='actif', max_length=10)),
                ('paydunya_token', models.CharField(blank=True, max_length=200)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_expiration', models.DateTimeField()),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('supprime', models.BooleanField(default=False)),
                ('date_suppression', models.DateTimeField(blank=True, null=True)),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quickpays_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quickpays',
                'indexes': [models.Index(fields=['createur', 'statut'], name='quickpays_createu_246fd6_idx'), models.Index(fields=['code'], name='quickpays_code_b0fad5_idx'), models.Index(fields=['statut', 'date_expiration'], name='quickpays_statut_f1eefa_idx')],
            },
        ),
    ]
