# Generated by Django 6.0.2 on 2026-03-24 18:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('pseudo', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('whatsapp_numero', models.CharField(blank=True, max_length=20)),
                ('whatsapp_verifie', models.BooleanField(default=False)),
                ('email_verifie', models.BooleanField(default=False)),
                ('niveau', models.CharField(choices=[('basique', 'Basique'), ('verifie', 'Vérifié'), ('business', 'Business')], default='basique', max_length=20)),
                ('identite_verifiee', models.BooleanField(default=False)),
                ('nom_verrouille', models.BooleanField(default=False)),
                ('numero_cni_hash', models.CharField(blank=True, max_length=64)),
                ('numero_mobile_money', models.CharField(blank=True, max_length=20)),
                ('code_parrainage', models.CharField(blank=True, max_length=8, unique=True)),
                ('nb_parrainages_actifs', models.IntegerField(default=0)),
                ('cotisations_creees_fenetre', models.IntegerField(default=0)),
                ('admin_role', models.CharField(blank=True, choices=[('super_admin', 'Super Admin'), ('moderateur', 'Modérateur'), ('support', 'Support'), ('finance', 'Finance'), ('verification', 'Vérification'), ('lecteur', 'Lecteur')], max_length=20, null=True)),
                ('fcm_token', models.TextField(blank=True)),
                ('ville_approx', models.CharField(blank=True, max_length=100)),
                ('pays', models.CharField(blank=True, default='TG', max_length=2)),
                ('date_inscription', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('parraine_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filleuls', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='SessionUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_info', models.CharField(blank=True, max_length=200)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('refresh_token_jti', models.CharField(blank=True, max_length=255)),
                ('est_active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_derniere_activite', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sessions_utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='UserGeoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('pays', models.CharField(blank=True, max_length=100)),
                ('pays_code', models.CharField(blank=True, max_length=2)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('timezone_field', models.CharField(blank=True, max_length=50)),
                ('isp', models.CharField(blank=True, max_length=200)),
                ('date_connexion', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geo_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_geo_logs',
            },
        ),
        migrations.CreateModel(
            name='VerificationIdentite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_recto_url', models.URLField(blank=True)),
                ('photo_verso_url', models.URLField(blank=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuvee', 'Approuvée'), ('rejetee', 'Rejetée')], default='en_attente', max_length=20)),
                ('prix_paye', models.IntegerField(blank=True, null=True)),
                ('note_admin', models.TextField(blank=True)),
                ('raison_rejet', models.TextField(blank=True)),
                ('date_soumission', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_decision', models.DateTimeField(blank=True, null=True)),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications_traitees', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'verifications_identite',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['pseudo'], name='users_pseudo_63a3db_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['telephone'], name='users_telepho_dce4c6_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['niveau'], name='users_niveau_739f88_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['pays'], name='users_pays_7710a8_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['date_inscription'], name='users_date_in_d295d5_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionutilisateur',
            index=models.Index(fields=['user', 'est_active'], name='sessions_ut_user_id_08b5bc_idx'),
        ),
        migrations.AddIndex(
            model_name='usergeolog',
            index=models.Index(fields=['pays_code', 'date_connexion'], name='users_geo_l_pays_co_fba09f_idx'),
        ),
        migrations.AddIndex(
            model_name='usergeolog',
            index=models.Index(fields=['user', 'date_connexion'], name='users_geo_l_user_id_613e6e_idx'),
        ),
    ]
