# Generated by Django 6.0.2 on 2026-03-24 21:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeRemboursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('raison', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuvee', 'Approuvée'), ('rejetee', 'Rejetée')], default='en_attente', max_length=20)),
                ('note_admin', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remboursements_traites', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_remboursement', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'demandes_remboursements',
                'indexes': [models.Index(fields=['statut', 'date_creation'], name='demandes_re_statut_b95fb9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_transaction', models.CharField(choices=[('payin', 'Pay-in'), ('payout', 'Pay-out'), ('remboursement', 'Remboursement')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('frais_kotizo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('frais_paydunya', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('complete', 'Complète'), ('echoue', 'Échouée')], default='en_attente', max_length=20)),
                ('canal', models.CharField(blank=True, choices=[('MOOV_TOGO', 'Moov Money'), ('MIXX_TOGO', 'Mixx by Yas'), ('TMONEY_TOGO', 'T-Money')], max_length=20)),
                ('paydunya_token', models.CharField(blank=True, max_length=200)),
                ('paydunya_reference', models.CharField(blank=True, max_length=200)),
                ('cotisation_id', models.UUIDField(blank=True, null=True)),
                ('quickpay_id', models.UUIDField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transactions',
                'indexes': [models.Index(fields=['user', 'statut'], name='transaction_user_id_f12e15_idx'), models.Index(fields=['type_transaction', 'statut'], name='transaction_type_tr_747862_idx'), models.Index(fields=['date_creation'], name='transaction_date_cr_8892e5_idx'), models.Index(fields=['paydunya_token'], name='transaction_payduny_635117_idx')],
            },
        ),
    ]
