# Generated by Django 6.0.2 on 2026-03-24 21:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Utilisateur'), ('assistant', 'Assistant')], max_length=10)),
                ('contenu', models.TextField()),
                ('source', models.CharField(choices=[('app', 'Application'), ('whatsapp', 'WhatsApp')], default='app', max_length=10)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_ia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'messages_ia',
                'ordering': ['date_creation'],
                'indexes': [models.Index(fields=['user', 'date_creation'], name='messages_ia_user_id_cc420f_idx'), models.Index(fields=['source'], name='messages_ia_source_7e86db_idx')],
            },
        ),
    ]
