# Generated by Django 6.0.2 on 2026-03-24 21:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.IntegerField(default=500)),
                ('active', models.BooleanField(default=False)),
                ('duree_jours', models.IntegerField(default=7)),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('lancee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promos_lancees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'promos_verification',
            },
        ),
        migrations.CreateModel(
            name='AlerteFraude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_alerte', models.CharField(choices=[('creation_rapide', 'Création rapide'), ('multi_comptes', 'Multi comptes'), ('signalements_multiples', 'Signalements multiples'), ('numero_suspect', 'Numéro suspect'), ('fraude_paydunya', 'Fraude PayDunya'), ('injection_ia', 'Injection IA')], max_length=30)),
                ('description', models.TextField()),
                ('statut', models.CharField(choices=[('nouvelle', 'Nouvelle'), ('en_cours', 'En cours'), ('resolue', 'Résolue'), ('faux_positif', 'Faux positif')], default='nouvelle', max_length=20)),
                ('data', models.JSONField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes_traitees', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes_fraude', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'alertes_fraude',
                'indexes': [models.Index(fields=['statut', 'date_creation'], name='alertes_fra_statut_f14ad8_idx'), models.Index(fields=['user', 'type_alerte'], name='alertes_fra_user_id_3c4c9d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Sanction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.IntegerField(choices=[(0, 'Avertissement'), (1, 'Restriction légère 3j'), (2, 'Restriction moyenne 7j'), (3, 'Dégradation niveau 30j'), (4, 'Fermeture temporaire'), (5, 'Bannissement permanent')])),
                ('raison', models.TextField()),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('appliquee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanctions_appliquees', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanctions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sanctions',
                'indexes': [models.Index(fields=['user', 'active'], name='sanctions_user_id_9c5c73_idx')],
            },
        ),
        migrations.CreateModel(
            name='TicketSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('priorite', models.CharField(choices=[('faible', 'Faible'), ('normale', 'Normale'), ('haute', 'Haute'), ('urgente', 'Urgente')], default='normale', max_length=10)),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('en_cours', 'En cours'), ('ferme', 'Fermé')], default='ouvert', max_length=10)),
                ('cree_par_ia', models.BooleanField(default=False)),
                ('note_resolution', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_fermeture', models.DateTimeField(blank=True, null=True)),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_traites', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tickets_support',
                'indexes': [models.Index(fields=['statut', 'priorite'], name='tickets_sup_statut_2d8726_idx'), models.Index(fields=['user', 'statut'], name='tickets_sup_user_id_870d1a_idx')],
            },
        ),
    ]
